const ActionTypes = {

    ADD_COURSE : 'ADD_COURSE',
    DELETE_COURSE : 'DELETE_COURSE',
    CHANGE_COURSE_INFO : 'CHANGE_COURSE_INFO',
    
    ADD_TIME : 'ADD_TIME',
    DELETE_TIME : 'DELETE_TIME',
    CHANGE_TIME_INFO : 'CHANGE_TIME_INFO',

    VIEW_TIMETABLE: 'VIEW_TIMETABLE',
    CLOSE_PREVIEW: 'CLOSE_PREVIEW'
}

export default ActionTypes;